package eu.xfsc.fc.core.service.oid4vp;

/*-
 * ---license-start
 * fc-service-core
 * ---
 * Copyright (c) 2022 - 2026 Contributors to the Eclipse Foundation
 * ---
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License, Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0.
 *
 * SPDX-License-Identifier: Apache-2.0
 * ---license-end
 */

import java.time.Instant;

/**
 * Short-lived OID4VP challenge that binds a presentation request state to one connector DID.
 *
 * <p>The challenge is created before the wallet response is received and is consumed during the
 * final connector binding step to prevent replay and cross-connector binding.
 *
 * @param id externally referenced challenge identifier stored as {@code challenge_id}
 * @param connectorDid connector DID that requested the bootstrap flow
 * @param nonce random challenge nonce generated by the catalogue
 * @param state OID4VP state associated with the generated presentation request
 * @param createdAt timestamp at which the challenge was persisted
 * @param expiresAt timestamp after which the challenge must no longer be accepted
 */
public record Challenge(
        String id,
        String connectorDid,
        String nonce,
        String state,
        Instant createdAt,
        Instant expiresAt
) {
    /**
     * Checks whether the challenge has expired at the supplied timestamp.
     *
     * @param now timestamp used as comparison point
     * @return {@code true} if {@code now} is after {@link #expiresAt()}
     */
    public boolean isExpiredAt(Instant now) {
        return now.isAfter(expiresAt);
    }
}
