package eu.xfsc.fc.core.service.oid4vp;

/*-
 * ---license-start
 * fc-service-core
 * ---
 * Copyright (c) 2022 - 2026 Contributors to the Eclipse Foundation
 * ---
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License, Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0.
 *
 * SPDX-License-Identifier: Apache-2.0
 * ---license-end
 */

import eu.xfsc.fc.core.dao.oid4vp.ConnectorBindingChallengeRepository;
import java.security.SecureRandom;
import java.time.Instant;
import java.util.Base64;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Application service for issuing, looking up and consuming OID4VP connector binding challenges.
 *
 * <p>A challenge connects a generated OID4VP state to a connector DID. The service keeps all
 * validity checks centralized so callers do not accidentally accept expired, consumed or revoked
 * challenge rows.
 */
@Service
@RequiredArgsConstructor
public class ConnectorBindingChallengeService {

    private final ConnectorBindingChallengeRepository repository;
    private final Oid4vpBootstrapProperties properties;
    private final SecureRandom secureRandom = new SecureRandom();

    /**
     * Issues a challenge with a newly generated OID4VP state value.
     *
     * @param connectorDid connector DID that starts the bootstrap flow
     * @return persisted challenge bound to the connector DID
     */
    @Transactional
    public Challenge issue(String connectorDid) {
        return issue(connectorDid, UUID.randomUUID().toString());
    }

    /**
     * Issues a challenge for an already generated OID4VP state.
     *
     * @param connectorDid connector DID that starts the bootstrap flow
     * @param state OID4VP state generated by the verifier library
     * @return persisted challenge with a random nonce and configured expiry
     */
    @Transactional
    public Challenge issue(String connectorDid, String state) {
        if (connectorDid == null || connectorDid.isBlank()) {
            throw new IllegalArgumentException("connectorDid must not be blank");
        }
        if (state == null || state.isBlank()) {
            throw new IllegalArgumentException("state must not be blank");
        }

        Instant now = Instant.now();
        Challenge challenge = new Challenge(
                UUID.randomUUID().toString(),
                connectorDid,
                generateNonce(),
                state,
                now,
                now.plus(properties.getChallengeTtl()));
        repository.save(challenge);
        return challenge;
    }

    /**
     * Finds a challenge by state without applying active-state predicates.
     *
     * @param state OID4VP state to resolve
     * @return matching challenge, or empty if the state is blank or unknown
     */
    @Transactional(readOnly = true)
    public Optional<Challenge> findByState(String state) {
        if (state == null || state.isBlank()) {
            return Optional.empty();
        }
        return repository.findByState(state);
    }

    /**
     * Finds a not yet consumed, not revoked and not expired challenge by state.
     *
     * @param state OID4VP state to resolve
     * @return active challenge, or empty if the challenge is unavailable or inactive
     */
    @Transactional(readOnly = true)
    public Optional<Challenge> findActiveByState(String state) {
        if (state == null || state.isBlank()) {
            return Optional.empty();
        }
        return repository.findActiveByState(state, Instant.now());
    }

    /**
     * Finds an active challenge by its challenge id and connector DID.
     *
     * @param challengeId persisted challenge identifier
     * @param connectorDid connector DID that must match the stored challenge
     * @return active matching challenge, or empty if the identifiers are blank or inactive
     */
    @Transactional(readOnly = true)
    public Optional<Challenge> findActive(String challengeId, String connectorDid) {
        if (challengeId == null || challengeId.isBlank()
                || connectorDid == null || connectorDid.isBlank()) {
            return Optional.empty();
        }
        return repository.findActiveByChallengeIdAndConnectorDid(
                challengeId, connectorDid, Instant.now());
    }

    @Transactional(readOnly = true)
    public List<Challenge> findAll() {
        return repository.findAll();
    }

    /**
     * Atomically consumes an active challenge for the supplied connector DID.
     *
     * @param challengeId persisted challenge identifier
     * @param connectorDid connector DID that must match the challenge
     * @return {@code true} when the challenge was consumed
     */
    @Transactional
    public boolean consume(String challengeId, String connectorDid) {
        if (challengeId == null || challengeId.isBlank()) {
            throw new IllegalArgumentException("challengeId must not be blank");
        }
        if (connectorDid == null || connectorDid.isBlank()) {
            throw new IllegalArgumentException("connectorDid must not be blank");
        }

        boolean consumed = repository.consumeIfActive(challengeId, connectorDid, Instant.now());
        if (!consumed) {
            throw new IllegalArgumentException(
                    "Connector binding challenge is expired, revoked, unknown or already consumed");
        }
        return true;
    }

    /**
     * Generates a URL-safe random nonce for a new challenge.
     *
     * @return base64url encoded random nonce without padding
     */
    private String generateNonce() {
        byte[] bytes = new byte[32];
        secureRandom.nextBytes(bytes);
        return Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);
    }
}
