package eu.xfsc.fc.core.service.oid4vp;

/*-
 * ---license-start
 * fc-service-core
 * ---
 * Copyright (c) 2022 - 2026 Contributors to the Eclipse Foundation
 * ---
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Apache License, Version 2.0 which is available at
 * https://www.apache.org/licenses/LICENSE-2.0.
 *
 * SPDX-License-Identifier: Apache-2.0
 * ---license-end
 */

/**
 * Result returned to the connector when a new OID4VP bootstrap presentation request is created.
 *
 * <p>The connector forwards the request URI to a wallet and keeps the state and challenge metadata
 * for the token redemption and binding sequence.
 *
 * @param state OID4VP state generated by the verifier library
 * @param requestUri URI or request object reference that the wallet should resolve
 * @param qrCodeUri URI suitable for QR-code based wallet handover
 * @param challengeId catalogue challenge associated with the request state
 * @param connectorDid connector DID for which the request was created
 */
public record PresentationRequestResult(
        String state,
        String requestUri,
        String qrCodeUri,
        String challengeId,
        String connectorDid
) {
}
