###
# ---license-start
# fc-service
# ---
# Copyright (c) 2022 - 2026 Contributors to the Eclipse Foundation
# ---
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: Apache-2.0
# ---license-end
###

{{- if .Values.did.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fc-service.did.fullname" . }}
  labels:
    {{- include "fc-service.did.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "fc-service.did.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fc-service.did.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "fc-service.did.fullname" . }}
          image: nginx:alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.did.service.port }}
          readinessProbe:
            httpGet:
              path: /.well-known/did.json
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            {{- toYaml .Values.did.securityContext | nindent 12 }}
          volumeMounts:
            - name: artifacts
              mountPath: /etc/did-artifacts
            - name: artifacts
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: artifacts
          configMap:
            name: {{ include "fc-service.did.fullname" . }}-artifacts
        - name: tmp
          emptyDir: {}
{{- end }}
