{{- if .Values.portal.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fc-service.portal.fullname" . }}
  labels:
    {{- include "fc-service.portal.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.portal.service.port }}
      targetPort: http
  selector:
    {{- include "fc-service.portal.selectorLabels" . | nindent 4 }}
{{- end }}
